# Kubernetes ServiceAccounts v1.24+
# Purpose: Define service-specific identities and RBAC configurations for RefactorTrack microservices
# Security: Implements principle of least privilege with enhanced security controls

---
# Analytics Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: analytics-service
  namespace: refactortrack
  labels:
    app: analytics-service
    component: analytics
    security-tier: restricted
    data-sensitivity: high
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    token-expiry: "8h"
    audit.kubernetes.io/log-level: "RequestResponse"
    security.kubernetes.io/description: "Service account for Analytics service with restricted permissions"
    security.kubernetes.io/last-updated: "2023-10-20"
automountServiceAccountToken: false

---
# Candidate Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: candidate-service
  namespace: refactortrack
  labels:
    app: candidate-service
    component: candidate
    security-tier: restricted
    data-sensitivity: high
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    token-expiry: "8h"
    audit.kubernetes.io/log-level: "RequestResponse"
    security.kubernetes.io/description: "Service account for Candidate service with restricted permissions"
    security.kubernetes.io/last-updated: "2023-10-20"
automountServiceAccountToken: false

---
# CRM Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crm-service
  namespace: refactortrack
  labels:
    app: crm-service
    component: crm
    security-tier: restricted
    data-sensitivity: high
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    token-expiry: "8h"
    audit.kubernetes.io/log-level: "RequestResponse"
    security.kubernetes.io/description: "Service account for CRM service with restricted permissions"
    security.kubernetes.io/last-updated: "2023-10-20"
automountServiceAccountToken: false

---
# Requisition Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: requisition-service
  namespace: refactortrack
  labels:
    app: requisition-service
    component: requisition
    security-tier: restricted
    data-sensitivity: high
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    token-expiry: "8h"
    audit.kubernetes.io/log-level: "RequestResponse"
    security.kubernetes.io/description: "Service account for Requisition service with restricted permissions"
    security.kubernetes.io/last-updated: "2023-10-20"
automountServiceAccountToken: false

---
# API Gateway Service Account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway-service
  namespace: refactortrack
  labels:
    app: gateway-service
    component: gateway
    security-tier: restricted
    data-sensitivity: medium
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
    token-expiry: "8h"
    audit.kubernetes.io/log-level: "RequestResponse"
    security.kubernetes.io/description: "Service account for API Gateway service with restricted permissions"
    security.kubernetes.io/last-updated: "2023-10-20"
automountServiceAccountToken: false