# Analytics Service Kubernetes Configuration
# Version: 1.0
# Kubernetes Version: v1.25+
# Dependencies:
#   - config-maps.yaml: analytics-config
#   - secrets.yaml: analytics-secrets
#   - service-monitors.yaml: analytics-monitor

---
# Analytics Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: refactortrack
  labels:
    app: analytics-service
    component: analytics
    tier: backend
    environment: production
spec:
  replicas: 1  # Initial replica count, managed by HPA
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: analytics-service
  template:
    metadata:
      labels:
        app: analytics-service
        security-context: restricted
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
        checksum/config: "${CONFIG_CHECKSUM}"
        seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
    spec:
      # Pod Security Context
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: analytics-service
          image: refactortrack/analytics-service:latest
          imagePullPolicy: Always
          # Container Security Context
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          ports:
            - containerPort: 8000
              protocol: TCP
              name: http
          # Resource Limits and Requests
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
          # Environment Configuration
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: postgres-host
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: postgres-port
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: postgres-database
            - name: ELASTICSEARCH_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: elasticsearch-hosts
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: analytics-config
                  key: mongodb-uri
          # Import all secrets from analytics-secrets
          envFrom:
            - secretRef:
                name: analytics-secrets
          # Health Checks
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 30

---
# Analytics Service Definition
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  namespace: refactortrack
  labels:
    app: analytics-service
    component: analytics
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: analytics-service

---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: analytics-service-hpa
  namespace: refactortrack
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: analytics-service
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60