# Kubernetes Secrets manifest v1.24+
# Purpose: Secure storage of sensitive configuration data with enhanced security controls
# Rotation policies and access controls implemented as per security requirements

apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: refactortrack
  labels:
    app.kubernetes.io/name: database-credentials
    app.kubernetes.io/part-of: refactortrack
    security.refactortrack.io/classification: highly-sensitive
    security.refactortrack.io/rotation-required: "true"
  annotations:
    security.refactortrack.io/rotation-schedule: "30d"
    security.refactortrack.io/last-rotated: "2024-01-01T00:00:00Z"
    security.refactortrack.io/owner: "database-admin"
    security.refactortrack.io/validation-required: "true"
immutable: true
type: Opaque
data:
  # Database credentials - Base64 encoded values
  # PostgreSQL credentials for primary database
  POSTGRES_USER: UkVGQUNUT1JUUkFDS19EQl9VU0VS
  POSTGRES_PASSWORD: UkVGQUNUT1JUUkFDS19EQl9QQVNTV09SRA==
  
  # MongoDB credentials for document storage
  MONGODB_USER: UkVGQUNUT1JUUkFDS19NT05HT19VU0VS
  MONGODB_PASSWORD: UkVGQUNUT1JUUkFDS19NT05HT19QQVNTV09SRA==
  
  # Elasticsearch credentials for search engine
  ELASTICSEARCH_USER: UkVGQUNUT1JUUkFDS19FU19VU0VS
  ELASTICSEARCH_PASSWORD: UkVGQUNUT1JUUkFDS19FU19QQVNTV09SRA==
  
  # Redis credentials for caching
  REDIS_PASSWORD: UkVGQUNUT1JUUkFDS19SRURJU19QQVNTV09SRA==

---
apiVersion: v1
kind: Secret
metadata:
  name: gateway-secrets
  namespace: refactortrack
  labels:
    app.kubernetes.io/name: gateway-secrets
    app.kubernetes.io/part-of: refactortrack
    security.refactortrack.io/classification: highly-sensitive
    security.refactortrack.io/rotation-required: "true"
  annotations:
    security.refactortrack.io/rotation-schedule: "7d"
    security.refactortrack.io/last-rotated: "2024-01-01T00:00:00Z"
    security.refactortrack.io/owner: "security-admin"
    security.refactortrack.io/validation-required: "true"
immutable: true
type: Opaque
data:
  # JWT authentication secrets
  JWT_SECRET: UkVGQUNUT1JUUkFDS19KV1RfU0VDUkVU
  JWT_REFRESH_SECRET: UkVGQUNUT1JUUkFDS19KV1RfUkVGUkVTSF9TRUNSRVQ=
  API_KEY: UkVGQUNUT1JUUkFDS19BUElfS0VZ

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-credentials
  namespace: refactortrack
  labels:
    app.kubernetes.io/name: monitoring-credentials
    app.kubernetes.io/part-of: refactortrack
    security.refactortrack.io/classification: sensitive
    security.refactortrack.io/rotation-required: "true"
  annotations:
    security.refactortrack.io/rotation-schedule: "90d"
    security.refactortrack.io/last-rotated: "2024-01-01T00:00:00Z"
    security.refactortrack.io/owner: "monitoring-admin"
    security.refactortrack.io/validation-required: "true"
immutable: true
type: Opaque
data:
  # Monitoring system credentials
  PROMETHEUS_ADMIN_PASSWORD: UkVGQUNUT1JUUkFDS19QUk9NRVRIRVVTX1BBU1NXT1JE
  GRAFANA_ADMIN_PASSWORD: UkVGQUNUT1JUUkFDS19HUkFGQU5BX1BBU1NXT1JE
  ALERTMANAGER_CONFIG: ewogICJnbG9iYWwiOiB7CiAgICAicmVzb2x2ZV90aW1lb3V0IjogIjVtIgogIH0KfQ==